name: dart_chat
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.1.1

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_hotreload:
  shelf_web_socket:
  stream_channel:
  equatable:
  fpdart:

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
